import Head from "next/head"

import Layout from "../../components/Layout"

import CategoryTittle from "../../sections/Explore/CategoryTittle"

import RecomendedService from "../../sections/Explore/RecomendedService"

import OurServices from "../../sections/Explore/OurServices"

import InterestedService from "../../sections/Explore/InterestedService"

export default function Explorar() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout withNav withFooter>
        <CategoryTittle />

        <RecomendedService />

        <OurServices />

        <InterestedService />
      </Layout>
    </div>
  )
}
