import Head from "next/head"
import Link from "next/link"
import { Breadcrumb, BreadcrumbItem } from "@chakra-ui/react"
import ZIcon from "../../../components/Icon"
import Layout from "../../../components/Layout"
import Title from "../../../sections/Explore/CategoryId/Contact/Title"
import PhotosDescription from "../../../sections/Explore/CategoryId/Contact/PhotosDescription"
import Comentaries from "../../../sections/Explore/CategoryId/Contact/Comentaries"
import Creator from "../../../sections/Explore/CategoryId/Contact/Creator"
import Assessment from "../../../sections/Explore/CategoryId/Contact/Assessment"
import { useRouter } from "next/router"

export default function Home() {
  const router = useRouter()
  const { categoryid, categoryitemid } = router.query
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout withNav withFooter>
        <div className="generalWrapper">
          <Breadcrumb separator={<ZIcon name="arrow-right" />} pt="10">
            <BreadcrumbItem>
              <ZIcon
                name="arrow-leftv2"
                className="mr1"
                size={11}
                pointer
                onClick={() => {
                  router.push("/explorar")
                }}
              />
              <Link href="/explorar" as={`/explorar`}>
                <a>Categoría</a>
              </Link>
            </BreadcrumbItem>

            <BreadcrumbItem isCurrentPage>
              <Link
                href="/explorar/[categoryid]"
                as={`/explorar/${categoryid}`}
              >
                <a>{categoryid}</a>
              </Link>
            </BreadcrumbItem>
            <BreadcrumbItem isCurrentPage>
              <Link
                href="/explorar/[categoryid]"
                as={`/explorar/${categoryid}`}
              >
                <a>{categoryitemid}</a>
              </Link>
            </BreadcrumbItem>
          </Breadcrumb>
        </div>
        <Title title={`Marketing para redes ${categoryitemid}`} />
        <PhotosDescription category={categoryid} />
        <Creator />
        <Assessment />
        <Comentaries />
      </Layout>
    </div>
  )
}
