import Head from "next/head"
import Layout from "../components/Layout"
import GetStarted from "../sections/Post/GetStarted"
export default function Explorar() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout withNav withFooter>
        <GetStarted />
      </Layout>
    </div>
  )
}
